#!/bin/bash
#
git read-tree -u -m HEAD "$1"

# Load Chruby to automatically load Ruby
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

# Hooks are run from .git/
# We need to go up a level to get to the project root
cd ..

bundle install --deployment

bin/build

